"""add scheduled crawls

Revision ID: 2a683f56ab56
Revises: 43bea125fb99
Create Date: 2026-06-16 15:35:34.587193
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2a683f56ab56'
down_revision: Union[str, None] = '43bea125fb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_crawls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_base_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_crawls')
    # ### end Alembic commands ###
