"""add credit packages

Revision ID: 96ea959cffd8
Revises: 2a683f56ab56
Create Date: 2026-06-16 16:14:20.944970
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '96ea959cffd8'
down_revision: Union[str, None] = '2a683f56ab56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
